/** Minimal L402Escrow ABI: enough for the client, the server and the settler. */
export const escrowAbi = [
  {
    type: "function",
    name: "computeChannelId",
    stateMutability: "pure",
    inputs: [
      { name: "payer", type: "address" },
      { name: "provider", type: "address" },
      { name: "token", type: "address" },
    ],
    outputs: [{ type: "bytes32" }],
  },
  {
    type: "function",
    name: "getChannel",
    stateMutability: "view",
    inputs: [{ name: "channelId", type: "bytes32" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "payer", type: "address" },
          { name: "provider", type: "address" },
          { name: "token", type: "address" },
          { name: "deposited", type: "uint256" },
          { name: "claimed", type: "uint256" },
          { name: "refunded", type: "uint256" },
          { name: "expiry", type: "uint64" },
          { name: "closeRequestedAt", type: "uint64" },
          { name: "exists", type: "bool" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "available",
    stateMutability: "view",
    inputs: [{ name: "channelId", type: "bytes32" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "cumulativeFloor",
    stateMutability: "view",
    inputs: [{ name: "channelId", type: "bytes32" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "delegations",
    stateMutability: "view",
    inputs: [
      { name: "payer", type: "address" },
      { name: "signer", type: "address" },
    ],
    outputs: [
      { name: "maxCumulative", type: "uint256" },
      { name: "validUntil", type: "uint64" },
      { name: "active", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "delegationNonces",
    stateMutability: "view",
    inputs: [{ name: "payer", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "computeAuthNonce",
    stateMutability: "view",
    inputs: [
      { name: "payer", type: "address" },
      { name: "provider", type: "address" },
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "duration", type: "uint64" },
      { name: "validBefore", type: "uint256" },
    ],
    outputs: [{ type: "bytes32" }],
  },
  {
    type: "function",
    name: "openChannel",
    stateMutability: "nonpayable",
    inputs: [
      { name: "provider", type: "address" },
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "duration", type: "uint64" },
    ],
    outputs: [{ type: "bytes32" }],
  },
  {
    type: "function",
    name: "openChannelWithAuthorization",
    stateMutability: "nonpayable",
    inputs: [
      { name: "payer", type: "address" },
      { name: "provider", type: "address" },
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "duration", type: "uint64" },
      { name: "validAfter", type: "uint256" },
      { name: "validBefore", type: "uint256" },
      { name: "authNonce", type: "bytes32" },
      { name: "authSignature", type: "bytes" },
    ],
    outputs: [{ type: "bytes32" }],
  },
  {
    type: "function",
    name: "topUp",
    stateMutability: "nonpayable",
    inputs: [
      { name: "channelId", type: "bytes32" },
      { name: "amount", type: "uint256" },
      { name: "newExpiry", type: "uint64" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "authorizeSigner",
    stateMutability: "nonpayable",
    inputs: [
      { name: "signer", type: "address" },
      { name: "maxCumulative", type: "uint256" },
      { name: "validUntil", type: "uint64" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "authorizeSignerWithSig",
    stateMutability: "nonpayable",
    inputs: [
      { name: "payer", type: "address" },
      { name: "signer", type: "address" },
      { name: "maxCumulative", type: "uint256" },
      { name: "validUntil", type: "uint64" },
      { name: "nonce", type: "uint256" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "invalidateDelegationNonce",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "revokeSigner",
    stateMutability: "nonpayable",
    inputs: [{ name: "signer", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "settle",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "voucher",
        type: "tuple",
        components: [
          { name: "channelId", type: "bytes32" },
          { name: "cumulativeAmount", type: "uint256" },
          { name: "nonce", type: "uint64" },
          { name: "validUntil", type: "uint64" },
        ],
      },
      { name: "signature", type: "bytes" },
      { name: "signer", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "settleBatch",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "vouchers",
        type: "tuple[]",
        components: [
          { name: "channelId", type: "bytes32" },
          { name: "cumulativeAmount", type: "uint256" },
          { name: "nonce", type: "uint64" },
          { name: "validUntil", type: "uint64" },
        ],
      },
      { name: "signatures", type: "bytes[]" },
      { name: "signers", type: "address[]" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "settleAndClose",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "voucher",
        type: "tuple",
        components: [
          { name: "channelId", type: "bytes32" },
          { name: "cumulativeAmount", type: "uint256" },
          { name: "nonce", type: "uint64" },
          { name: "validUntil", type: "uint64" },
        ],
      },
      { name: "signature", type: "bytes" },
      { name: "signer", type: "address" },
    ],
    outputs: [
      { name: "paid", type: "uint256" },
      { name: "refund", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "requestClose",
    stateMutability: "nonpayable",
    inputs: [{ name: "channelId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [{ name: "channelId", type: "bytes32" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "CLOSE_CHALLENGE_PERIOD",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint64" }],
  },
  {
    type: "event",
    name: "ChannelOpened",
    inputs: [
      { name: "channelId", type: "bytes32", indexed: true },
      { name: "payer", type: "address", indexed: true },
      { name: "provider", type: "address", indexed: true },
      { name: "token", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "expiry", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "VoucherSettled",
    inputs: [
      { name: "channelId", type: "bytes32", indexed: true },
      { name: "provider", type: "address", indexed: true },
      { name: "cumulativeAmount", type: "uint256", indexed: false },
      { name: "delta", type: "uint256", indexed: false },
      { name: "fee", type: "uint256", indexed: false },
      { name: "nonce", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SignerRevoked",
    inputs: [
      { name: "payer", type: "address", indexed: true },
      { name: "signer", type: "address", indexed: true },
      { name: "effectiveAt", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CloseRequested",
    inputs: [
      { name: "channelId", type: "bytes32", indexed: true },
      { name: "by", type: "address", indexed: true },
      { name: "claimableAt", type: "uint64", indexed: false },
    ],
  },
] as const;

/** Reduced ERC-20 ABI. */
export const erc20Abi = [
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ type: "bool" }],
  },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "name", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
] as const;
