[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["../../node_modules"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 1000
via_ir = false
evm_version = "cancun"
fs_permissions = [{ access = "read", path = "./out" }]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", chain = 8453 }
base_sepolia = { key = "${BASESCAN_API_KEY}", chain = 84532 }
